Repository HYF-Class23/home, pull requests merged in 2024-02, with the labels that each got.

#42 add smita bio
  student-bios/Smita81.md
  student-bios/img/2524ce_9e44d973146a46f4bf8a69f586c84167~mv2.png
  student-bios/polyannameira.md
Labels: week-1

#44 Tarun bio
  package-lock.json
  student-bios/img/birthplace.png
  student-bios/img/hobby.png
  student-bios/img/hyf.png
  student-bios/img/journey.png
  student-bios/img/tarun.png
  student-bios/tarunpurswani.md
Labels: indvidual

#37 add stefanBio
  .cspell.json
  student-bios/img/stefanPhoto.jpg
  student-bios/stefan-000.md
Labels: md

#51 Yurii bio
  student-bios/img/YuriiPhoto1.jpg
  student-bios/juryp.md
Labels: md

#53 add EnnyFRANS.md and img
  student-bios/EnnyFRANS.md
  student-bios/img/ennyphoto.jpg
Labels: indvidual

#60 add info about vidushi
  student-bios/vidushiseksaria.md
Labels: md

#58 Add Allans student bio
  student-bios/AllanSaku.md
  student-bios/img/IMG_allan.jpg
  student-bios/juryp.md
Labels: indvidual, md

#67 add info about vidushi
  student-bios/vidushiseksaria.md
Labels: indvidual

#74 Add Ernesto's bio
  student-bios/img/Foto de Neto Calderòn.jpg
  student-bios/img/FotoNetoCuba.jpg
  student-bios/img/IMG_1278.jpg
  student-bios/img/IMG_5559.JPG
  student-bios/netocalderon.md
Labels: student-bio

#92 add kevin bio
  student-bios/Kev-Ose.md
  student-bios/img/family_kev.jpeg
  student-bios/img/kev.jpg
  student-bios/img/kev_pro.jpg
Labels: indvidual, md
